const pt_br: Strings = {
  appName: 'EHOBABA',
  welcome: 'Bem Vindo',
  login: 'Entrar',
  email: 'Email',
  password: 'Senha',
  confirmPassword: 'Confirmar Sehnha',
  loginWithFacebook: 'login com facebook',
  loginWithGoogle: 'login com google',
  lastMatches: 'Últimas Partidas',
  lastMatch: 'Última Partida',
  playedRecently: 'Jogou recentemente',
  pendingRatings: 'Votações Pendentes',
  home: 'Home',
  babas: 'Grupos',
  profile: 'Perfil',
  myBabas: 'Meus grupos',
  myProfile: 'Minha conta',
  name: 'Nome',
  bornDay: 'Data de nascimento',
  position: 'Posição',
  flag: 'Bandeira',
  createProfile: 'Criar perfil',
  forgotPassword: 'Esqueci minha senha',
  fillEmail: 'Insira seu email para que possamos prosseguir',
  editImage: 'Editar Imagem',
  addImage: 'Adicionar Imagem',
  search: 'Pesquisar...',
  save: 'Salvar',
  games: 'Jogos',
  age: 'Idade',
  vel: 'vel',
  chu: 'chu',
  pas: 'pas',
  mar: 'mar',
  dri: 'dri',
  rac: 'rac',
  gol: 'gol',
  def: 'def',
  fal: 'fal',
  des: 'des',
  ass: 'ass',
  goBack: 'Voltar',
  goFoward: 'Avançar',
  velocity: 'Velocidade',
  kick: 'Chute',
  pass: 'Passe',
  marking: 'Marcação',
  dribble: 'Drible',
  guts: 'Raça',
  cast: 'Elenco',
  events: 'Eventos',
  score: 'Placar',
  vote: 'Votação',
  doVote: 'Realizar votação',
  babaCode: 'Código do Grupo',
  joinTheBabaCast: 'Junte-se ao elenco do ',
  justCopyTheCodeBelow: 'Basta copiar o código abaixo e colar no app:',
  inviteForCast: 'Convide amigos para o elenco',
  joinBaba: 'Entrar em um grupo',
  insertCode: 'Inserir código',
  close: 'Fechar',
  share: 'Compartilhar',
  send: 'Enviar',
  cancel: 'Cancelar',
  confirm: 'Confirmar',
  createBaba: 'Criar grupo',
  createGame: 'Criar jogo',
  place: 'Local',
  addEvent: 'Adicionar evento',
  deleteEvent: 'Remover Evento',
  deleteEventAux: 'Tem certeza que deseja remover o evento permanentemente?',
  addPlayer: 'Adicionar Jogador',
  selectPlayer: 'Selecionar Jogador',
  notPlayedAnyMatchYet: 'Você ainda não jogou nenhuma partida.',
  noPendingRates: 'Sem votações pendentes',
  noPlayersAddedInGame:
    'Sem jogadores adicionados ao jogo, adicione jogadores do seu elenco e eles aparecerão aqui',
  notInAnybaba:
    'Você ainda não está em nenhum grupo, crie ou entre em um já existente',
  noPlayersInCast:
    'Sem jogadores no elenco, convide amigos e eles aparecerão aqui ao aceitarem',
  noGamesCreated: 'Sem jogos criados',
  noEventsAdded: 'Sem eventos adicionados',
  ratingClosed: 'Avaliação fechada',
  ratingOpenButNoRated: 'Avaliação aberta, aguardando voto dos jogadores',
  defaultServiceError:
    'Erro ao contactar o servidor, tente novamente mais tarde',
  fieldMustBeFilled: 'Campo precisa ser preenchido',
  mustContainOnlyNumbers: 'Campo precisa conter apenas números',
  codeMustContainSixDigits: 'Código precis conter 6 digítos',
  mustSelectOnePlayer: 'Jogador não selecionado',
  mustSelectOneEventType: 'Tipo de evento não selecionado',
  defaultError: 'Algo deu errado, tente novamente mais tarde',
  mustHaveNoSpaces: 'Não contém espaços',
  mustHaveMinimunLength: 'Contém ao menos 8 caracteres',
  hasOneUpperCase: 'Contém ao menos 1 letra maiúscula',
  hasOneLowerCase: 'Contém ao menos 1 letra minúscula',
  hasOneDigit: 'Contém ao menos 1 digito',
  hasOneSpecialCharacter: 'Contém ao menos 1 caractere especial',
  passwordsMustMatch: 'As senhas precisam ser iguais',
  wrongEmailOrPassword: 'Email ou senha inválidos',
  emailAlreadyInUse: 'Email já está sendo utilizado',
  sendEmail: 'Enviar email',
  emailNotFound: 'Email não encontrado nos registros',
  emailAlreadySent: 'Mensagem já foi enviada, tente novamente em 30 minutos',
  wrongCode: 'Código inválido',
  codeExpired: 'Código expirado',
  invalidEmail: 'Email inválido',
  haveACode: 'Possuo um código',
  intertCodeSended: 'Insira o código enviado para o seu email',
  insertEmailAndCode: 'Insira o email e o código enviado',
  changePassword: 'Trocar senha',
  insertNewPassword: 'Insira a nova senha',
  removePlayerFromBabaTitle: 'Remover Jogador do Baba?',
  removePlayerFromBabaMessage:
    'Tem certeza que deseja remover esse jogador do baba?',
  removePlayerFromGameTitle: 'Remover Jogar do Jogo',
  removePlayerFromGameMessage:
    'Tem certeza que deseja remover esse jogardo do jogo?',
  addGuest: 'Adicionar Convidado',
  guestName: 'Nome do convidado',
  performance: 'Desempenho',
  performanceEvaluation: 'Avaliação de Desempenho',
  ranking: 'Ranking',
};

export default pt_br;
